services:
  - type: web
    name: quill-cove-backend
    env: node
    buildCommand: npm install --prefix Backend
    startCommand: npm run start --prefix Backend
    plan: free
    autoDeploy: true
    envVars:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}

  - type: web
    name: quill-cove-frontend
    env: static
    buildCommand: npm install --prefix QuillCove && npm run build --prefix QuillCove
    startCommand: serve -s QuillCove/dist
    plan: free
    autoDeploy: true
    envVars:
      VITE_API_URL: ${REACT_APP_API_URL}